version: '3.8'

services:
  influxdb:
    image: influxdb:latest
    restart: always
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=pccodes
      - DOCKER_INFLUXDB_INIT_PASSWORD=Pascal123*
      - DOCKER_INFLUXDB_INIT_ORG=pccodes
      - DOCKER_INFLUXDB_INIT_BUCKET=pccodes
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=tokenpccodes
    ports:
      - 8086:8086
    volumes:
      - influxdata:/var/lib/influxdb
  server:
    container_name: app-server
    restart: always
    build:
      context: ../
      dockerfile: ./.docker/Dockerfile
    ports:
      # - Host-Port:Contanier-Port
      - '4000:4000'
    depends_on:
      - "influxdb"
    volumes:
      - server:/app/
    hostname: app_server

  client:
    container_name: app-client
    restart: always
    stdin_open: true
    build:
      context: ../
      dockerfile: ./.docker/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - client:/app

volumes:
  server:
  client:
  influxdata: